---
title: "GBMcRegMap_Figure5_code"
author: 
- "pawlakG PAWLAK Geoffrey"
- "ConYel Konstantinos Geles"
date: "Mon Dec 04 2023, Last Update: Thu Feb 29 2024 `r format(Sys.Date(), '%a %b %d %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    df_print: paged
  pdf_document:
    toc: yes
    toc_depth: 3
  html_notebook: null
---

# Global libraries 
load libraries
```{r setup libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# functions
source(here("Figures_code", "Fig_misc_functions", "misc_functions.R")) 
here()
# data wrangling libraries
library(dplyr)   #
library(stringr) #
library(tibble)  #
library(vroom)   #
library(purrr)   #
library(tibble)  #
library(forcats) #
library(tidyr)   #

# Differential enrichment 
library(edgeR)   #

# plot
library(ggplot2)      #
library(ggheatmapper) #
library(patchwork)    #
```

# load data
```{r}
inf_mat <- here("Figures_code", "data", "influence_U87MG_U87MGRR50_U87MGOFF.csv") %>% 
    dplyr::rename("Gene_ID" = "...1") %>%
    column_to_rownames("Gene_ID") %>%
    as.matrix()

inf_mat <- inf_mat[,c("U87MG_1", "U87MG_2", "U87MG_3",
                      "U87MGOFF_1", "U87MGOFF_2","U87MGOFF_3",
                      "U87MGR50_1", "U87MGR50_2",  "U87MGR50_3")]

group <- rep(c("U87MG", "OFF", "R50"), each = 3)
design <- model.matrix(~0 + group)
colnames(design) <- colnames(design) %>%
    str_remove("group")

rownames(design) <- colnames(inf_mat)
```

# DIGs 
```{r}
myargs = list("OFFvU87MG" = "OFF-U87MG", "R50vU87MG" = "R50-U87MG",  levels=design)

con_mat <- do.call(makeContrasts, myargs)

data.fit <- lmFit(inf_mat, design)
data.fit <- contrasts.fit(data.fit, con_mat)
data.fit <- eBayes(data.fit, robust = TRUE)

t <- con_mat %>%
    colnames() %>%
    purrr::set_names() %>%
    map(~data.fit %>%
            topTable(coef = .x,
                     number = nrow(.),
                     adjust.method = "BH",
                     sort.by = "p" ) %>%
            as_tibble(rownames = "gene")) %>%
    bind_rows(.id = "contrast") %>%
    dplyr::rename(AveInf=AveExpr)
cut_off_padj <- 0.05
cut_off_LFC <- 0.6
t_tp <- t  %>%
    mutate(DI = case_when(
        logFC > cut_off_LFC & adj.P.Val < cut_off_padj ~ "Up",
        logFC < -cut_off_LFC & adj.P.Val < cut_off_padj ~ "Down",
        TRUE ~ "Not Sig.")
    )
```

# Fig 5B Influence heatmap  -----
```{r}
### get the group and prepare a tibble ----
sample_annot <- tibble( sample = rownames(design),
                        group = group) %>%
    mutate(group = as_factor(group))

depen_list <- t_tp %>%
    filter(AveInf > 0) %>%
    arrange(desc(AveInf)) %>%
    group_by(contrast) %>%
    group_split() %>%
    map(~ arrange(.x, desc(logFC)) %>%
    dplyr::slice(1:20, (n()-3) :n()) %>%
    ungroup() %>%
    pull(gene) %>%
    unique() ) %>%
  unlist() %>%
  unique()

depen_list <- c(depen_list, "MDM2", "EGFR", "PAX8", "CDKN2B",
      "NKX2-5", "CCNE1", "AJUBA", "TP63",
     "AHR", "SMAD3", "CCND1", "FOSL1") %>%
    unique() %>%
  str_subset("ZNF506|TRIM22|BATF2|AHDC1|ZNF347|FOXO4", negate = TRUE)

inf_mat_tb <- inf_mat %>%
    t() %>%
    as_tibble(rownames = "sample") %>%
    left_join(sample_annot, by = "sample") %>%
    dplyr::select(sample, group, all_of(depen_list)) %>%
    group_by(group)

### genes to pick for hmap ------
genes <- inf_mat_tb %>%
    ungroup %>%
    dplyr::select(-c(sample, group)) %>%
    names

to_scales <- inf_mat_tb  %>%
    dplyr::select(-c(sample)) %>%
    pivot_longer(-group) %>%
    pull("value") %>%
    quantile

grp_clo <- c("#00AFBB", "red" , "#8B0000") %>% set_names(group %>% unique())
### plot hmap  -----
gr_gghm <- ggheatmap(inf_mat_tb,
                     colv = "sample",
                     rowv = genes,
                     hm_colors = 'RdBu',
                     hm_color_values = scales::rescale(c(min(to_scales), 0, max(to_scales))),
                     scale = TRUE,
                     center = TRUE,
                     fontsize = 13,
                     show_dend_row = TRUE,
                     show_dend_col = FALSE,
                     show_colnames = FALSE,
                     cluster_rows = TRUE,
                     cluster_cols = FALSE,
                     dend_prop_row = 0.2,
                     show_rownames = TRUE,
                     group_prop = 0.03,
                     group_colors = grp_clo,
                     colors_title = "Scaled TF/coTF \ninfluence (log2 UQ)")

ht_ahC <- gr_gghm +
    plot_layout(guides = 'collect')

### save the plot        -------
ggsave(plot     = ht_ahC,
       device   = "png",
       filename = here("Figures_code", "Figure_5", "Fig5B_heatmap.png"),
       units    = "in",
       width    = 8,
       height   = 10,
       dpi      = 300)
```

